# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pas',
            name='task',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 13, 45, 16, 821469, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdi',
            name='knowledge_area',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 13, 45, 29, 92911, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdi',
            name='office',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 13, 45, 32, 229103, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
