# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20160213_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 2, 13, 16, 19, 10, 508630, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
