# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_auto_20160213_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
