# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_auto_20160213_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='department',
            field=models.BooleanField(default=False),
        ),
    ]
