# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_topic_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
