# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 13:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20160214_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentari', 'verbose_name_plural': 'Comentaris'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departaments'},
        ),
        migrations.AlterModelOptions(
            name='pas',
            options={'verbose_name': 'Pas', 'verbose_name_plural': 'Pas'},
        ),
        migrations.AlterModelOptions(
            name='pdi',
            options={'verbose_name': 'Pdi', 'verbose_name_plural': 'Pdi'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiant', 'verbose_name_plural': 'Estudiants'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Assignatura', 'verbose_name_plural': 'Assignatures'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultes'},
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Data de publicaci\xc3\xb3'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='pas',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'users/%Y/%m/%d', verbose_name=b'Imatge'),
        ),
        migrations.AlterField(
            model_name='pas',
            name='task',
            field=models.CharField(max_length=200, verbose_name=b'Tasca'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='knowledge_area',
            field=models.CharField(max_length=200, verbose_name=b'Especialitat'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='office',
            field=models.CharField(max_length=200, verbose_name=b'Despatx'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'users/%Y/%m/%d', verbose_name=b'Imatge'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'users/%Y/%m/%d', verbose_name=b'Imatge'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'any'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_author', to=settings.AUTH_USER_MODEL, verbose_name=b'Autor'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Data de publicaci\xc3\xb3'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name=b'\xc3\x89s public?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Data actualitzaci\xc3\xb3'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='priority',
            field=models.CharField(choices=[(b'LOW', b'Baixa'), (b'MEDIUM', b'Mitja'), (b'HIGH', b'Alta')], default=b'MEDIUM', max_length=9, verbose_name=b''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_receiver', to=settings.AUTH_USER_MODEL, verbose_name=b'Receptor'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[(b'OPEN', b'Obert'), (b'CLOSED', b'Tancat'), (b'RESPONDED', b'Respost')], default=b'OPEN', max_length=9, verbose_name=b'Estat'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name=b'Assumpte'),
        ),
    ]
